### ISSUE TITLE
Web interface stability issues

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-explorer#97]
Currently the ooni-explorer is very unstable and will often times be stuck in a state where it will not show any measurements and all the API endpoints will timeout.

I made some changes to collect better debug level information and it seems like the issue is with connecting to the database:

```
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: Error in GET /reports/count?where=%7B%22probe_cc%22:%22ET%22%7D: errorName=Error errorMe
ssage=Timeout in connecting after 5000 ms
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: errorStack=Error: Timeout in connecting after 5000 ms
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: at null.<anonymous> (/home/ooni-api/ooni-api/node_modules/loopback-datasource-juggler/li
b/datasource.js:2121:10)
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: at null._onTimeout (/home/ooni-api/ooni-api/node_modules/loopback/node_modules/continuat
ion-local-storage/node_modules/async-listener/glue.js:188:31)
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: Error in GET /reports?filter=%7B%22fields%22:%7B%22test_name%22:true,%22input%22:true,%2
2probe_cc%22:true,%22test_start_time%22:true,%22id%22:true,%22probe_asn%22:true%7D,%22where%22:%7B%22probe_cc%22:%22ET%22%7D,%22offset%
22:0,%22limit%22:100,%22order%22:%22test_start_time+DESC%22%7D: errorName=Error errorMessage=Timeout in connecting after 5000 ms
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: errorStack=Error: Timeout in connecting after 5000 ms
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: at null.<anonymous> (/home/ooni-api/ooni-api/node_modules/loopback-datasource-juggler/li
b/datasource.js:2121:10)
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: at null._onTimeout (/home/ooni-api/ooni-api/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
Aug  6 14:36:23 ip-172-30-2-158 node-ooni-api: at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
Aug  6 14:36:28 ip-172-30-2-158 node-ooni-api: Error in GET /nettests: errorName=Error errorMessage=Timeout in connecting after 5000 ms
Aug  6 14:36:28 ip-172-30-2-158 node-ooni-api: errorStack=Error: Timeout in connecting after 5000 ms
Aug  6 14:36:28 ip-172-30-2-158 node-ooni-api: at null.<anonymous> (/home/ooni-api/ooni-api/node_modules/loopback-datasource-juggler/lib/datasource.js:2121:10)
Aug  6 14:36:28 ip-172-30-2-158 node-ooni-api: at null._onTimeout (/home/ooni-api/ooni-api/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
Aug  6 14:36:28 ip-172-30-2-158 node-ooni-api: at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
Aug  6 14:37:17 ip-172-30-2-158 node-ooni-api: Connection fails:  { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
Aug  6 14:37:17 ip-172-30-2-158 node-ooni-api: It will be retried for the next request.
Aug  6 14:37:17 ip-172-30-2-158 node-ooni-api: Error: connect ETIMEDOUT
Aug  6 14:37:17 ip-172-30-2-158 node-ooni-api: at errnoException (net.js:905:11)
Aug  6 14:37:17 ip-172-30-2-158 node-ooni-api: at Object.afterConnect [as oncomplete] (net.js:896:19)
```

While in this state I can confirm that the issue is indeed the database as trying to connect to it also via another client times out.

cc @anadahz

**Comment by anadahz** [comment]
It seems that the network connectivity issue occurred (according to logs) only in Aug 6.

The web interface still seems to be randomly in an unresponsive state.

**Comment by hellais** [comment]
I think this has been resolved (at least I am no longer seeing stability issues in the statuscake monitoring logs)
